version: "3.8"

services:
    nginx1:
        image: nginx:latest
        container_name: nginx1
        volumes:
            - .:/var/www
            - ./nginx/nginx1.conf:/etc/nginx/conf.d/default.conf:ro
        ports:
            - "8081:80"
        depends_on:
            - php1

    nginx2:
        image: nginx:latest
        container_name: nginx2
        volumes:
            - .:/var/www
            - ./nginx/nginx2.conf:/etc/nginx/conf.d/default.conf:ro
        ports:
            - "8082:80"
        depends_on:
            - php2

    php1:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php1
        volumes:
            - .:/var/www
        depends_on:
            - mysql_db

    php2:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: php2
        volumes:
            - .:/var/www
        depends_on:
            - mysql_db

    mysql_db:
        image: mysql:8.0
        container_name: mysql_db
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: password
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql

volumes:
    db_data:
